### ISSUE TITLE
Is further customization possible?

### ISSUE THREAD

**Issue by L11K** [Aeryax/docker-spoilerbot#2]
Is further customization possible or would I need to build another image? 

I need to customize texts like (hover to reveal spoiler) and other stuff to my language. 

Thank you in advance.

**Comment by Aeryax** [comment]
I would be glad to add this feature, but https://github.com/TimboKZ/discord-spoiler-bot doesn't implements i18n or something similar at the moment. You may open a PR/Issue on the other repository.

**Comment by L11K** [comment]
I was talking about this [this](https://github.com/TimboKZ/discord-spoiler-bot/commit/4f82ec7aa2b7c5057f0c02ac80cd80598c4c788d). The customization that is already available. 

I tried to build the image myself and make the variables  [(for every customization than you can do with the non-docker version)](https://github.com/TimboKZ/discord-spoiler-bot/wiki/Configuration), but I'm too new to Docker and didn't manage to do it.

Timbo's code feels like a labyrinth to me tbh.

**Comment by Aeryax** [comment]
Oh my bad, we can do it now. I'll try to add this to the docker image ASAP.
